### ISSUE TITLE
ubuntu 22.04 build failed due to missed #include <cstring>

### ISSUE THREAD

**Issue by khatymov** [zproksi/bpatch#23]
Need to add this header to some files:
- consoleparametersreader.cpp
- flexiblecache.h
- streamreplacer.h

**Comment by VladimirTakeda** [comment]
@khatymov could you provide the way you build the app (with screenshots if necessary)? The pipeline in Github Actions includes ubuntu build and it works fine.

**Comment by khatymov** [comment]
Sure @VladimirTakeda 
![image](https://github.com/user-attachments/assets/f4455b54-ab91-4847-af99-fb83115e7845)
![image](https://github.com/user-attachments/assets/967125bd-7a0a-4e19-8135-f2ae3996126f)
![image](https://github.com/user-attachments/assets/2c73934c-55ce-4568-968c-2faca4e2b639)

**Comment by khatymov** [comment]
Well, I just built bpatch in docker container ubuntu:22.04  locally with g++ 11.4.0 (default version).  g++ in my WSL (ubuntu22.04) is higher than it should be.
___
My wsl ubuntu 22.04:
 - g++: version 12.3.0
___
docker container ubuntu:22.04:
 - g++: version 11.4.0
I updated g++ to 12.3.0 in docker and tried to build and got the initial problem with the header. 
___
So the problem is in g++ version. @zproksi @VladimirTakeda should we close the ticket?

**Comment by zproksi** [comment]
memcpy has been declared in <cstring> according cppreference. Hence we should include it.
#include <cstring> has been added to "stdafx.h" - update.
